LOG_DIR: "logs"

SOURCE_DIR: "data/india/"
SOURCE_VIDEO_PATH: "data/india/08_30fps.mp4"
RESULT_DIR: "results/india/"
TARGET_VIDEO_PATH: "results/india/result_08-08_30fps.mp4"

TRACK_CHECKPOINTS_DIR: "results/csv/"
TRACK_CHECKPOINTS_CLASS: ["obj_tracker_id", "class_id", "avg_speed_kmph", "entry_direction", "exit_direction", "entry_time", "exit_time"]

MODELS_DIR: "models/"
MODELS_WEIGHTS_8X: "models/yolov8x.pt"
MODELS_CONFIG_8X: "models/yolov8x.yaml"
MODELS_WEIGHTS_8N: "models/yolov8n.pt"
MODELS_CONFIG_8N: "models/yolov8n.yaml"